#!/usr/bin/python3

# Dota2 Senate



# def simulate(senate):
#   N = len(senate)
#   blocked = [False for i in range(N)]
#   for i in range(N):
#     # round i
#     for j in range(1,N):
#     

NAMES = {
  "R": "Radiant",
  "D": "Dire"
}


class Senator:

  def __init__(self, *, party, idx, disable):
    self.party = party
    self.idx = idx
    self.disable = disable
    self.prev_ = None
    self.next_ = None


  def __repr__(self):
    status = "disabled" if self.disable else "active"
    return f"Senator({self.party},{self.idx},{status})"

def preprocess(senate, N):
  head_r = None
  tail_r = None
  count_r = 0
  head_d = None
  tail_d = None
  count_d = 0
  for i in range(N):
    if senate[i] == "R":
      s = Senator(party="R", idx=i, disable=False)
      if head_r is None:
        head_r = s
        tail_r = s
      else:
        tail_r.next_ = s
        s.prev_ = tail_r
        tail_r = s
      count_r += 1
    else:
      s = Senator(party="D", idx=1, disable=False)
      if head_d is None:
        head_d = s
        tail_d = s
      else:
        tail_d.next_ = s
        s.prev_ = tail_d
        tail_d = s
      count_d += 1

  return (
    head_r,
    tail_r,
    count_r,
    head_d,
    tail_d,
    count_d,
  )

def _other(p):
  return "R" if p == "D" else "D"


def simulate(senate, N):

  print(f"{(senate,N)=}")
  head_r, tail_r, count_r, head_d, tail_d, count_d = preprocess(senate, N)

  for round_idx in range(N):
    print(f"starting round {round_idx}")

    curr_r = head_r
    curr_d = head_d

    while curr_r is not None or curr_d is not None:
      print(f"{(curr_r,curr_d)=}")
      if curr_r is None:
        curr = "D"
      elif curr_d is None:
        curr = "R"
      elif curr_r.idx < curr_d.idx:
        curr = "R"
      else:
        curr = "D"

      if curr == "R":
        senator = curr_r
        target = curr_d
        (next_r, next_d) = (curr_r.next_, curr_d.next_ if curr_d is not None else None)
      else:
        senator = curr_d
        target = curr_r
        (next_r, next_d) = (curr_r.next_ if curr_r is not None else None, curr_d.next_)

      if target:
        if target.prev_ is None:
          if curr == "R":
            head_r = target.next_
          else:
            head_d = target.next_
        else:
          target.prev_.next_ = target.next_
        if target.next_ is None:
          if curr == "R":
            tail_r = target.prev_
          else:
            tail_d = target.prev_
        else:
          target.next_.prev_ = target.prev_
        print(f"disabled {target}")
      else:
        return curr

      (curr_r, curr_d) = (next_r, next_d)

  raise ValueError("vote should have been called already")


def winner(senate):
  N = len(senate)
  if N == 0:
    return None

  return NAMES[simulate(senate, N)]

def main():
  print(winner("RD"), "R?")
  print(winner("RDD"), "D?")
  print(winner("RDDR"), "R?")
  print(winner("RDDDRR"), "D?")
  print(winner("RDDRRD"), "R?")
  print(winner("DRRDRDRDRDDRDRDR"), "R?")
  print(winner("RRRRRDRRDRDRRDRRDDRRDRDRDDDRRRRDRRRDDRDRDDDRRRDRDRRRDDDRRRDDRDRRDRDDDRRDDRRRDDDRDRRRRRRRRRDDRDRDDDDDRRDRRDRDRDDRDDRDRRDDRDRRRDDDDDDDRRDRRRRRDRRDRRDDDRDDRDRDRRDRRDDDDRRDDRDRDRRRRDDRDRRRRRDRRDDRRRDRDRRDDRDDDDDDDDDDDRRRRRRRRDRRRDDRDDRDDDDDRDDRRDRRDDRRDDRDDRDRRDRDDDDRDDRDRDRRDDDDDRDRDRRRRDRDRDRDDRDRRRRRDRRRRDDDDDDDRDRRDRRRDRDRRDRRDRDDRDRDRDRDDDDRRRDDDDDRDDRDRRDDRDDDDRRRRRDRRRDDRDDRDDRRRRRRRDRRRDDDDRRDDDDRDRRDDRRDDDRDRRRRRDDDRRRRRDRRRRRDRDRDRRRDRRRDDDDRRRRRDRRDDRDRRRDRDDDRDRDRRRDDDRDRDRDDDRRDDDDRDDRDRRRDDRDDDRRRDRRDRRDDRDDDDDRDDDRDDDDRDRRDRRDDRRDDRRRRDDRRRDRRDRDRDDDRRRDDDDRDDDDDDRDRRDRRRDDDRDDRDRRRDDDDDDRRDRRDDRDDRDRDRDDDRDDRRRDRDDRDRRRRRDDRDRRDRRDDDDDDRDRRRRDRRRRDDRRRDDRDRDDDDRRDRDDDRRDDDRDRDDRRDRRDDRRRDRRRDRRDRRRDDRRRDDDDRRDDDRRDRRDRDRRRRRDDRRRRRRDDRRDRRDDDDRRDRDDDDDDDRDDRDDDDDRDRRRDDRRRRRDDRDDDRRDDDDDRDRDDRRRRDDDRDDRDDRDRRDDRRRDRDDRDRDRDRDRRRDDDRDRDDRDDRRDRDRDDDRRDDDRDRRRDDRDDRRRRDRRRRRDRDRRRRRRDDDRRRDRRRRRDDDDRRDRDDRRDRRRDDDDDRDDRRDRDDRRRRDRRRDRRDDDRDRRRRRDDRRRDDDRRRDRRDRDDDDDDDRDRRDRDRDRDDDDDRDRRDDRRRDDDRDRRDDDDRRRDRRDDRDRRRRDRRDDDDDDDDRRRDDDDDDDRRDRDDDDDDDDRRDRRDDDRRDRRRDRDRDRRDDDDRDDRDDDRDRRDRRDRDDDRDRDRDDDRRRDDRDRRDDRRDRRRDRDDRDDDRRRRRRDDDDRDDDDDRRDRDDRDRRRDDRRRDRRDDDDRRDDRDDRDDRRDDRDRDDDRDDDRRRRDRDDDDRDDRDRDRDRDDRRRRRDRRDDDDDDDDDDRRRDRDDRRDRDRDDDDRRDDRDRDDDRDDDDDDRDDRRRDRDDRRDDDDRDRDDRRDRRRRDRRDRRDRDRDDRDRDRRRDRRDDDRDRDDDRDDRRRDDDDRDRDDRDRRRDDRRRRDRDDDDRRDRRDRDRDRRRDRDDRRDDRDDDRDDRDDRDDRDRRRRRRRDRRDRDRRDRRRRRRRDRDDRRRDRDRDRDDDRDDDDDRRDDRRDDDRRDRDRDRRRRDDRDDRRDRRRDRDDRDRRRDRRRRDDDRRRDRDDRDDDDDRDRDDDRRRDRDRDRRDRDDDDDDRRDRRRRDDDDRDRDRDDRRDRDRRDDRRDRDRDDDDDRDDRRDDRRRDRRRDDRRDRDRDRRDDRRDRDDRRRDDRDRDDDDRRDRRRDDDDRDRRRRDRDRDRDDRRDDRDRRDDDDDRDRRDDDRDDRDRDRDRDRDRRRDDRDDRRDDDDRRRDDRDRDRDRRDRRRRDDRDDRRRRDRRRDDDRRRRRRDRDRRRRDDDRDRDRDRRRRDDRRRRRDDRRDDDRRRRRDRRRDDRDRDDDRRRDRRRRDRDRDRDRDRDRRRDDRRRRDDDDRRDRRDRDRRRRDRDDRRDRDRRDDDRRRRRRDRRRRRRRDDRDDDDDRDRDDDDDDRRRRRRDRRRRDRDRRRDRDDDRDDDRRRDDDDRDDDDRDRDDDRDRDRDRDDDDRRDRDDRDRDDRRDDDRDDDRRRDDDRRDRDDRDRDRDRRRRRDRRDRRRRDDDDDRRRDDRDRRRDDDDRRRDDRDDRRDRRDDDDRRRRRDDRRRDRRDRRRDRRRRRDRRDDDDRRDRRDDRDDRRRRDDDDDRDDDDRRDDRRRDDDRDRRDDRRDRDDRDRRRRRRRDRDRDDRRRRRRDRRRRDRDDDDRRDRDDRRDRDRRRRRDDDRRRRRRRDDDRDDDDRDRRDDRDDDRRDRRRRRRDDRRDRDDDRDDDRRRDRDDDDDDDDDRDRDRDDRRRDDDDRRDRDRDRRDDRRDDDDDDDRDRRRDRRDRRRDDDRRRRDRDDRDDRDDDRRRDDDDDDRDDDRDRDDDRDRDRRDDRDDRDRDRRDDDRDDDDRDDDRRRDRRRRRDDDRDRRDRRRDDDRDRRDDRRDRDRRRRRRDDDRRRDDDRRRRDRRRRDRDDDRDRRRRRDRDRRRDDRRRDDRRRRDRDDDRRRRDRDRDRDRRDDRRDDDDRDDDDDRRRDRDRRRRRRRDRRRRRRDRDRDRRRDDRRRDDDDRDDRDRDRDRDRDRRDRDRDRDDRRRDRRDRDRRRDRDRRRRRRRRRDDDRDDRRDRDRRRRDRDDRRRRRRRRRRDDRDDRRRRDRDDRDRRDDDRDDRDRRDRDRRDDRDDRDRDRDRRDRDRRDDRDRDDDDDRDRRDRDDRDRDDRDRRDDDDDRRRDRDDRRRDRRRRDRDDRDRDDRRRRRDDRDRRDRDDDRRRRRRRRDRRRDDRDRDDDRDRDDDRDDDDRRDDDDRDDRRDDDDRRRDRRDDRDRDDDRDDDRDDDDDDDDRRRRRRDDRRRRRRRRDRDRDDDDDDDRDRRDDDDRDRRRRDRDRDRRRRRRDDDRDDRDRRRRDRRRDDRDRDDDDRRRRDDDRDRRDDDRRRRDRRDRDDDDDDRRRDDDRDDRRRRRRDRDRDDRDDDRDDDRRDDRDRDRDRDDDRDRDDDRDRDDDRDRRRRRDDDDRRDRRDDRDRDDDRDDRDRDRDDDDDRRRRDDRRRRDRDDDRDRRDRRRDRDDDDDDDDRRDDDDRDRRDDDDRDDRRDRRRRRDRRDRRDDRRDDDRRRRDDDRDRRRRRDDDRRRDDRRRDRDRDDDDRRRRDDRRDRDDDRRRDDDRDRRRDDDDDRRRDRDRDDDDDRDDDRRDRDRDRRRRRDDRDDRDDDRDDRRDRDDDDRRDDDRDDDRRRRDDDDRRDDDRDRDDDRDRRDRRDRDRRDRRDRDRDRDDRRRDDDRDDRRDDDRDDRRRDDDRRDRRRDDRDDDRDRRDDRDRRDDDRRDDRRRDRDDDRDDDDRDRDRDDDDDRDRDRRDRDRDRRRRRDRRRRRRRDDRRRDDRRRRRRRRDDDRRRRDRRRRDRDRRDDRDDRDDRRDDDRRDRRDDDDDDDDRDRDRRDDDDRDDDRRRRRDDDDDRDRDDDDDDDDRDRDDDRDRRRDDDDRRRDRDDRDRDDDRDDDDDDRRRRDDRDRDDRRDDDRDDDDRRDRDRDDDRRDDDDRRRDRDRDRRRDDDRDDRRDRRDDRRDRRDDRRDDRRRRDRRRDDRDDDDDDRRRDDDRDRRDRRDDDRRDRDDRDDRRDRRRDDRDRDDDRDDDDRDDDRDRRDDRDRDDDDDRRDDRRDDDDDDRRRRDRDDRDDRRRRDRRDDDRDDRRRRRRDDDRRRRDDDRDDRDDRRRDRRRRDRDDRDRDDRRRRDRDDRDDRDDDDDRRDRRRRRDRRRDRDDRDRRRRDRRDDDRDRDDDRDDDRDDDRRRRDRRDDRDDDRDDRDDRRRDDRDRDRRRRRDDRDRRDRDRRDDRRDRDRDDRRDRDDDRRRRDRDDRDDDDRRRRRDDDDDDRRDRDRRRDDRDDDRRDRDDDRRDRRDRDRDDDDDDDRRDDRRDDDRDRDRRDDDDRDRDDDRDRDRDRRDRRDRRRDRDRDRRRDRRDRDRRRDRRRRDDDDRDRDRRRRDRDRRRDRRRRDDRDDDRDDDDDDRDDDDRDRRDDDRDDDRRRDRDDDRRDDRDRDRRDRDRRRDRRRRRRDRRRDRDRDDRRRRDRRDRDDDDRRDDDDDDDDRDRDRRRRDRDDDDDRDDRRRDRDRDDDRDRRRRRDDDDDDRRDRRDRRDDDRRRRDRRRRDDDDDRDRRDRDRRDDRDRRRDRDDRRDDRDRRRRRRDRDDDRDDRDRRDDRDDRRRRRDDRRRDDDDRRDRDRDRRDDDDRDRRRRRRRDRDDDDDRDRRRDDRDRDDRRDDRDDDRRDRRRRRRDRRDDDRRRRRRRDRDDDRRRRDRDDDDDRRRDDDRRDRRDDDDRDDRRRDDRRRRDDRDRDDDDRDDRRDDDRDRRDDDRRDDDRDDRDDRDDDDRDRDRRRDDRDDRDRRDRRDDDDRDDRRRDDRDDRDDDRRRDDDDRDDRRDRDDDDRRRRDRDRDDDDRRDRRRRRDRDRRDRDRRRDDRRRDDRRRDDRRRDDDRRDRDDRDDDRDRDDRRDRRRRRDDDRRRDDRRDRRRDRDDRDRDDDRRDRRRRDRRDDRRRRDRDRRDRRDRDDRDDDDDRRDRRDRRDRRRDDRDRRDDDDRDDDDRDRRDDRDRRRDDRRDRRRDRDDDDDRRRRDDDRRRRDRRRRDRDDDDDDDDDRDDDDDDRDRRDRDDDDRRDDRRRDDDDDDDDDDRRDRRRDDDDRDDDDDRDDDRRRDRRDRRRDRRDDRRRDRDRRRRDRDDRRDDDRRDDDDRDRDRDDDRRDDDDDRDRDDRDDRRDDDRRRRRRRRRDRDDRDRDRRDDRRRDDDRRRRDRRRRRRDDDRRRRRRRRRRRRRDRDRDRRDDRDRDDRRRRDDRDDRDRDRRRDDDDRDRDDDRDRDRRDDDDRRDRDDDRRDRRRDRDRRRRDDRDDDDRDDRDDRDDRRDRDRDDRDRRDDRDDDDDRRDRDRDDRRDRDDDRDRDDDRDDRDRDRDRDDDDDDRRRDRDDDDRDRDRRDDRDDRRRRDRDRDRDRDDRRDDRRRDDRRRRDRRRDDRDDRRDDRDDRRRRDRRDRDDRDDDDDDDRRRRDDRDDRRRRRRRRRRDDRRDDDDRDDDDRDDDDRRDRRRDDRRDDDDRDDRRDDDRDRDRDDDDDRRRDRDDRRDDRDRDRDRRDDDDDDRRRDRDRDDDDRRDDRDDRRRDRDDDRRDDRDRRDDRRRRDDDDRRRRDDDRDDDDRDDRDDRDRDRDRDDDRRRRRDRRDRDRRDDDDDDDRRDRRDDRRDDDRDRDDRRDDRRDRRRRRRRDDDRRRRDDRRDRDRRDDDRRRRDRRRDRRRRRRRDRDDDDRRDRDDRRDRRDDDRRDDRRDRDRDRRRRDRRDDRDDDDDRDRRDDRDDRRDDRRDDDRDDRDDDRDDDRRDRDDDDDRDDRDDDDRDDRRRRDRDDDRRRRRRRDRRDRRDDDDDRRDRDDRDDRDDRDRRDDRDRRDDDDRRRDRRRRDDRDRRRRRRDRDRRDDRDDRRRDRDDRDDRRRRDDDDDDRRRDDRDRRDRDRRRDRDRRRRRDDDDDDRRDDRDRRDDDRDDDDDRDRRRDRDDDDRRDRDRRRDDDRRDDDRDRDRDRRRDRDRDRDRDRRDDDDRDDRDDDDDRRDDDDRRRDDDRDDDRRDRDDRDDDDDDRRRDDRDDRRDRRDDDDDDRRDRRRDDDDRRRDRDRDRDRRRRDDDDDDRDDDDDRDDRDDRDDDDDRRDDDRRDDDRRDDDDRDDDRDRRDRRDRDDRDRRRRRDDRDDRDRDDDDDDDRRDDDDRRRDRDRRDDRRRRRRDDRDDRRRDDDDRDDDDDDRDRDDRDDDRRDDRRRRDDDRRRRDRRDDRRRRRDDDDDDRDDDDRDRRRRDDDRRRRRDDDDDDRRRDRDDRRDRDDDDRDRRRDDDDDRDRRRRDDDRDDRDDDRRDRDRRRRDRDRDDDDDDDRDDDRRDDRDRRDDRRDDDDRDRRDDRRRDRDDDDDRRDRDRRRRDDRRRDDRDRRRDRDRRDDDRRDDRDRDRRRDDDRRRRDDRDRDDDDRDRRRRDDRRRRRRRDRDDDRRRRRRRRRRRDDRRRDRDRDRDDDRRRDRRRDRRDDRRRDDDRRRDRDRDDRRDDRDRDRRRDDDDDRRDDDDDRRRDRRDRDDDDRRDDRDDRDRDDDDDDDRRRDDRRDDRDRDDRDRRDDRRRRDRRDDDDDRDRRRDDRDDRDDDDRRRDRRRDRDRRRDRRDRRRRRRDRDDRDDRDRRRDDRDDDDDDDDRDRRRRDDRRRDRDRDRDRDRDRDDDDDDRRDRDDDDDDRDRDRDDRDDRDDRDDDRRDRDRDRRRRRDDDDDRRRRDRDRDDDRRDDDDDDDRDDDDDDRRRDDRDRRRDDDDRRDRRRDRRDDDDDRDDRRRDDDRRDRDDRDRRRRRDRRRRDDDRDDDRDRRRRRDDDRRDRDDDDRDRDRRRDDRDDRRRRDDDDRDRDDDRDRRDDRDRDRRRDRDDRRDDRRRRRDDDRRRDRDRDRDDDRRDDDDRDRRRDDRRDDRDDRDRRRRRRDRRDDRRDRDRDDDDDDRRDDDRDRRDRDRRRDRDDDRRDDDDDDDRDRRDDRRRRDDRRRDRDRRRRRRRDDDRDRDDDDRRRRDDDDRDRDRRDDRDRDRRDRDDRRRRDRRRDDRRRDDDRRRDRRDRRRDRDRDDRDRDDDDRDDRRRDRDRDDRDRDDRRRDRRDRRDRRDDDDRRRDDDDRDDDDDDDDDDRRDDDDRDDRDRRDRRDDDDRRRDDDDDDRDDRDDRDDRRDRRRRRRRRDRRDDDDDDRDDRDRRRRDRRDRRDDRRDRRDDRDDDDDDRDRRRRDRRDRDDRDDDRRDDDDRRRDRDRDRRRRRRDDDDRDDRRDRRRDDDRDDDDDDDRRDRDRRDRRRDRDDRDDDDDDRDRRRDRRRDDDDRRDRDRRRDDRRRRDDDRRDRDRDRRRDRDRDDRRDRRRRDDRDRRDDRDDDRDDRDDDDRDDRRDDRDRDDDDRRDRRRRDDDDRRDRRDRDRDRDRRRRRRDRDDRDDDDDRRDRDRDDDDDDRRRDDDDRRDRRRDRRRRRDRDDRDDDRRDDRRRRRRDDDDRRDDRDRDDDDRRRDDRRDRDDDRRRRDDDDRDDDRDDDRDRRRRDRDRDRDDRDRDDRDDRDRRRDRDRRDDRRRRRDDRDDDDDRDRRRDDRRRRDDRDDDDRDRRRRDRDRRRRRRRDRRDDRRDDDDDDDRRRRDRDDDDDRRRDRDRRDRDRRRDDRDRRRRRRRDRRRRRRRDDRDDRDDDDRRRDRDRRDDDDRRDRDDRDDDDRRRDDRDRRDDDDDDRRRRRRDRRRDDRRRRRRDDDRRRRRDDRDDRDRRDRRRRDRRDRDDRDRRDRRDRRDRDRDRDRRDRDDDRRRRRDDDRDDRDRDDRRDRRRRRRRDDRRRRRDRDDRRRRRRDRDRDRRDRDDRRDDDRRRDRDRDDDRDDDDDRRDRDRRDRRRRRRRDDDDRRRRDRRDDDRDRRDDDRDRRDDRRRRRDDRDDDDRRRDRRDDRDRRRRRRRDDRDDDDDRRDDDDDDDRRDDDDDDDDRDRDDDDDDDDRDRRDRRDDDDDDDDRDRRRDDRRDRDDRRDRDDDRRRRRRDRDDDRDRDDDRDRRRRDRRDDDDDDDDDDDRDDRDDDRDRRDRRDDRRRRDDDDRRRDRDDRDRRDDRRRRDRRDDRRRDDRRDDRRDDRDRDRDDDRDDRDDDDDRDRRRRDRDRRDDRDDRRRDRDDRDRDDDRRDRDDDRRRDDRRDRDRDDRDDDRRDRDDRDRRDRDDDDDRRRDDRDRRDRDDDDRDRRDRRDRDRRDDDDRDDDRDDDRRRDDDRRRRDDRRRDRRRDRRRRRDRDDDDDDRDRRDDDDRDDRRDRDRDDRRRRDRRDDDRDDDDRRRRRRRRDRDRDDRRDRRRDRDRDRDRRDDRRDDRDDDRDRRRDDDDDRRRRDDDDRDRRDDRRRRDRDRRDRDRDRRDRDDDDRRRRRRRDDRRDRDDRDDDRRRDRRDDDRRDRDRDDDDRDRDRRDDRRDDRDDRDDDDRDDDRDDDRDDRRDRDRRDDRDDDDRDDDDDDRRRDDDDDRDDRDRDDRDRDDRRDRRRDRRDDRRDRRDRDRDDDRDRRDDRRRDRDRRDDRRRDRRRDRRRDDRRRDDRRDRDDDRRRDDRRRRDRRDDDRDDRDRRDDDRDDDRRDDRDDDDRRRRDDDRDRDDRRRRRRDRRDRDDRRRDDRRRDRRDDRDRDDDDDRRRRDRRDRDRDDDRDRDDRDRRRDRDRDDDDDDRRRRDRRRRDDDDRDRDDRRRRRDRRRRRRDRRDDDDRRDRRRDRDRRDDRDDRDDDDRRRDRDDRDRRDRRDDDRRRDDRRDDRDDRRRDRRDRDDRDRDDRDDRDRDRRRRDDRRDDDRRDDRDRDRDDRRDRDRDDRDRRRRRRRRDDRRRDDRRRDRRDRRDDRRDRRRDRDDDDRRDRRDRDRDDDDDDDDRDRDDDDRDDDRDRRRDDRDRRRDDRRRRRDDDRDRDDDDRRDDRDDRDRDDRDRDRRRDDRRDRDRRRRRRDRDDRDRDRRDRDRDDRRRDDRRRRRRDRDDDDRDDDRRRDRRRRRDRDRRDDDRDRDRDDRRRDDRDRRDDRRDRDRRDDRRRRDRRRRDRDRDDDDRDDDDDRDDRRDDRDRRDRDDDDDRDRRDRRRDRDRRRRDRDDDRRRDRRDDRRRDDDRDRRRDDRDDRDRDDDRRDDDDRRRDRRDDDDDRDRRRDDRRDDRRDDDRRRDRRDDDRDRDDRRDDDRRDRDDRDDDRDDRDRRRDRRDDDRDRDDRRRDRDDRRDRDRDDDRRDDRDDRDRRRRDDRRDRDRDDRDRRRRRRDDRRDRDDDRRRRRRDDDRDDRRRDDDRRRDRDRRDDDDDRDDDRRDDRRDDRRDDDRRDRDDDDDDDDDRDRDDDDDDDRRDRDRDRRRRRRRDRDRRDRRRRDRRRDDDDRDDDDDDDRDRDRRDDDDDRDDDRRDDRDDDRRRDDDRDRDRDRDRRRRDDDDDRDDRRDRDRRRDRDRDRRRRRRDRDDDDRRRDDDRRDDRDDDDRDRDRDDRRDDDDRRDDDRDRRDDDDDDDRRRRDDRDDRDDDDRDDDDDRDDRRDDDRRRRRRRDDDDRDRDDRRDRDRRDRDRRDDRRDDDDRRRRRRDDDDDRRRDRRRDDDDDRRDRDRDRRRRRRRDDDRRDDRRDRDRDRRRDDRDRRDDDRRDRRDDRRDRRRRDRDRDRRRRRRRRRRDRDRRRRRDRDDRDDRDDRRRRDRRDRDDRDDDDRDDDRRDDRDDRRDDDDRDRRDRDDRRDDDRDDDDRDRDDDRRDRDRRRDRRDDDRDRRRRDDDRRDRDRRDDRDRRRRRRRDDDRRDRDDRDDDRDDRDDDDRRRRDDDDRRDRDRRRRRDRRRRDDDRRDDRDDRDRDRRRRRDDRRDRDDDDDDRDRDDRRDDRRRRRDDRDRRDRDDDDDDRDRRRDRDDRDDRRDRRRDRRRRRDDRDDRRDRDDRDDRDRRRDRDRDRDRDRRRRDRDRDRRDRDRRRDRDDRRDRRRRDDRRRDDRDRRDDDRRDRRRRDRDRDDDRDDDDDDRRDDDDDDDDRDDDRDDRDDDRRDRRDDDRDRRRDRDRRRRDDRRRDDRRDDRDRDDDDRRRRRRRDDRDDDDDDDRDDRRRDDRDDDRDRDRRDDRRRDRDRDDRDRDRDRRRRRRDRRDDRRDDDRRRDRRRDDDRRDRRRDRRRDRRRRDDDRDDDRDDRDDRRDRDRDRDDDDDRRDRRDDRDDRDRDRRRRRRRDDDDRDRDRRRRDRRRDDRRDRDDRDDRRRRRRRDDDDRRRRDRRRRDDDDDRDDDDDDDDDDDDDRRRRDRDDDDRRRDDRDDRDDRDDRRRRRRDDRDRDRRDRDDRRRRRDRDDDDDRRRDRRDRRRRDRRDDRDRDRDDRDDRDRRDRDDDDDRDDDRRDDDDDRDDDDRDRRRDDDDDRRDDRDRDDDRDRRDDDRDRDRDRRRDDRRDDRRRRDRDDDRRDDRDDDRRDDDRDDDDDRRDRRDDDRRRDDRRDRRRRDDDRRDDDDRDRRRRDRRRDRDRDDRDRRDDDDDRDRDDDRDRRRRDDDDDDRRRDRRRDRRDRRDRDRDDDDDDDRDDDRDRDRDDDRRRDRDRRDRDDRDRRRRRDRDRDDRRDDR"))

main()







"""

DRRDRDRDRDDRDRDR
xxxx x x xx x x   --> R







"""



